### ISSUE TITLE
Mensagem -  Tempo máximo

### ISSUE THREAD

**Issue by aprix** [aprix/projetao20152uag#105]
Ao se tentar renovar o estacionamento, caso o usuário escolha um tempo que somado ao tempo anterior ultrapasse o tempo máximo permitido, a seguinte mensagem é exibida: "Veículo já estacionado, tempo máximo permitido já adquirido". Entretanto, a renovação não será concretizada pela restrição do tempo máximo. Assim, a mensagem de erro deve ser alterada.

**Comment by DiogoEspinhara** [comment]
Corrigir palavra "at" do comando :
$response['Error'] = "Tempo máximo ultrapassado, só é possível colocar at $max_time minutos";
