### ISSUE TITLE
Melhorias nos relatórios

### ISSUE THREAD

**Issue by renanlf** [aprix/projetao20152uag#109]
- Gerar PDF
- Ao realizar as buscas as opções selecionadas na busca devem ser mantidas.
- Trocar o Id do usuário pelo apelido
- Ordenar o relatório pela data e hora de forma que o primeiro resultado seja o mais recente.
- Ao iniciar o relatório o campo Ano poderiam começar no ano atual.
- Colocar a data no formato dd/mm/aaaa
- Campos com valores monetários colocar como R$ 99,99

**Comment by VinieSantana** [comment]
Todas as melhorias( exceto a formatação das datas e a geração de PDF) foram implementadas no pull 
request #107

**Comment by VinieSantana** [comment]
Implementadas no pull request #116, o PDF foi substituído por uma página HTML pronta para impressão
