### ISSUE TITLE
WebService - Tratar mensagem de erro referente a duplicidade de cartão de crédito.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#117]
Ao tentar cadastrar o mesmo cartão de crédito pela segunda vez (usuário logado), o Webservice retorna a mensagem do erro em inglês.

**Comment by renanlf** [comment]
Qual a mensagem @DiogoEspinhara ?

**Comment by DiogoEspinhara** [comment]
Duplicate entry...
