### ISSUE TITLE
Simbolo status tickets

### ISSUE THREAD

**Issue by aprix** [aprix/projetao20152uag#14]
Ao se adicionar mais de um ticket, o simbolo de status do segundo ticket em diante e mostrado como vermelho.

**Comment by aprix** [comment]
A hora ate a qual o ticket estará valido e salva de forma errada. Ativei um segundo ticket para outra placa as 15,24, a validade registrada foi ate 14,26.

**Comment by renanlf** [comment]
Eduardo, informe por favor teus valores de entrada.

Em 18 de outubro de 2015 15:25, aprix notifications@github.com escreveu:

> A hora ate a qual o ticket estará valido e salva de forma errada. Ativei
> um segundo ticket para outra placa as 15,24, a validade registrada foi ate
> 14,26.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprix/projetao20152uag/issues/14#issuecomment-149036789
> .

## 

Att,

Renan Leandro Fernandes

Graduando em Ciência da Computação pela Universidade Federal Rural de
Pernambuco, Unidade Acadêmica de Garanhuns(UFRPE/UAG).

Lattes: http://lattes.cnpq.br/4329681764449719

**Comment by DiogoEspinhara** [comment]
Issue duplicada. O problema abordado aqui está sendo resolvido pela issue 22 - https://github.com/aprix/projetao20152uag/issues/22
