### ISSUE TITLE
#Interface# Compra avulsa de novo ticket

### ISSUE THREAD

**Issue by aprix** [aprix/projetao20152uag#16]
Falta explicação ao usuário de que não e possível a compra de um novo ticket avulso antes que o ticket atual expire, que para isso e necessária a realização do cadastro.

**Comment by DiogoEspinhara** [comment]
Entra em contradição com outra US, renovação de vaga. Isso será tratado de maneira diferente, e somente quando a US de renovação for implementada.

**Comment by DiogoEspinhara** [comment]
Não será necessário se cadastrar para renovar um ticket.
