### ISSUE TITLE
WebService - A hora atribuída ao novos tíquetes (pagamentos) atrasada.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#22]
Devido a problemas com privilégios de acesso, será necessário criar uma função que corrija o fuso horário da data e hora atribuída a um novo tíquete(pagamento).

Exemplo:

CREATE FUNCTION NOW_CORRECT()
RETURN DATETIME //Ou outro tipo de dados aqui.
BEGIN

END;

**Comment by DiogoEspinhara** [comment]
Continuação do exemplo:

CREATE FUNCTION NOW_CORRECT()
RETURN DATETIME //Ou outro tipo de dados aqui.
BEGIN
      RETURN now() + INTERVAL 50 MINUTE;
END;

**Comment by renanlf** [comment]
Função criada e adicionada ao script.

**Comment by DiogoEspinhara** [comment]
Me enganei sobre a quantidade de minutos de atrasado. Na verdade, o servidor está 40 minutos atrasados, e não 50 minutos.

**Comment by DiogoEspinhara** [comment]
Desconsiderem o último comentário. O certo é 50 minutos de atraso.
