### ISSUE TITLE
WebService - Função de cadastro de usuário.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#30]
A função no WebService deverá receber um JSON no formato abaixo:
{"Email": "email", "Nickname": "apelido", "CPF": "00000000000", ''Password":"MD5 da senha"}

A reposta do servidor deverá seguir o padrão das funções já implementadas. Se for sucesso, retornar:

{"id": IdUsuário}

Recomendações: fazer uma única função para insert e update.

**Comment by DiogoEspinhara** [comment]
Correção: o JSON de entrada será:

{"id": inteiro, "Email": "email", "Nickname": "apelido", "CPF": "00000000000", ''Password":"MD5 da senha"}

Obs.: se o id for zero, significa que é um novo usuário

**Comment by renanlf** [comment]
Diogo, usuário não tem nome, só quem tem são os vendedores e fiscais.

**Comment by DiogoEspinhara** [comment]
Renan, se estiver falando de Nickname, se refere ao apelido.

**Comment by renanlf** [comment]
Sim, este mesmo, no nosso projeto de banco não tinha nome ou apelido para o usuário.

**Comment by DiogoEspinhara** [comment]
Tem apelido em Wiki/Documentos/Banco/Modelo. A gente decidiu pegar o apelido para enviar emails de notificações, confirmações, e etc.

**Comment by DiogoEspinhara** [comment]
Colocar a primeira letra maiúscula da variável id -> Id. Na resposta também.

O atributo CPF no banco de dados deve ser string (varchar). Se for inteiro, os zeros a esquerda são removidos.
