### ISSUE TITLE
WebService - Cadastro de cartão de crédito.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#31]
A entrada para o cadastro( insert or update ) será:
{"Id": inteiro, "Name":"NOME NO CARTÃO", "Number": "1234567890123456", "Flag": "MasterCard ou Visa", "MonthValidate": inteiro, "YearValidate": inteiro}

Obs.: concordamos que o CSC não será armazenado no cadastro. Lembrando que se o Id for zero significa que é um novo cadastro.

A saída, no caso de sucesso, será: {"Id": inteiro}

**Comment by DiogoEspinhara** [comment]
Mais uma observação. O JSON de entrada deve conter um par de chave Status:
{"Id": inteiro, "Name":"NOME NO CARTÃO", "Number": "1234567890123456", "Flag": "MasterCard ou Visa", "MonthValidate": inteiro, "YearValidate": inteiro, "Status": "True ou False"}

**Comment by renanlf** [comment]
Diogo, faltou uma chave: a chave do usuário que possui este cartão, irei chamar de "IdUser" ok?

**Comment by DiogoEspinhara** [comment]
Perfeito Renan, ótima observação.

**Comment by renanlf** [comment]
A validação do numero do cartão também será feita no cadastro?

**Comment by DiogoEspinhara** [comment]
Exatamente, conforme a issue #19 .

**Comment by DiogoEspinhara** [comment]
Necessário mudar o tipo de dado do atributo número do cartão. Atual: int(16), Novo Tipo: char(16).

Observação: lembrar de mudar os comandos de SQL Insert e Update no WebService.
