### ISSUE TITLE
Remoção do número do cartão de crédito

### ISSUE THREAD

**Issue by renanlf** [aprix/projetao20152uag#49]
Quando o usuário remover o cartão, por questões de segurança o número do cartão deverá ser trocado por algum valor único que não o possa identificar.

**Comment by DiogoEspinhara** [comment]
Necessário alterar a função do WebService. A mudança se refere a não validar o número do cartão quando o status for False (0).

**Comment by renanlf** [comment]
Ok, farei isso agora.
