### ISSUE TITLE
Alteração em tabela do banco de dados

### ISSUE THREAD

**Issue by VinieSantana** [aprix/projetao20152uag#54]
Alterar campo state_registration da tabela institution para que ela n seja not null.

**Comment by renanlf** [comment]
Não seria melhor fazer conforme @DiogoEspinhara comentou, inserindo vazio? Neste caso eu trocaria de INT para VARCHAR, o que acham?

**Comment by VinieSantana** [comment]
VARCHAR! Segundo @aprix, a inscrição estadual não possui restrição de quantidade de digitos, tornando INT inviável.

**Comment by renanlf** [comment]
@VinieSantana , pode fechar a issue?
