### ISSUE TITLE
Cadastrar Instituição

### ISSUE THREAD

**Issue by aprix** [aprix/projetao20152uag#61]
Números e símbolos especiais são permitidos nos campos de Bairro, Cidade e Estado.

Título dos campos não é traduzido nas mensagens de erro. Ex.: "O campo state registration deverá conter um número inteiro."

Mudar linguagem na mensagem de erro de "O campo X deverá conter um número inteiro." para "O campo X deverá conter um valor numérico."

Campo número também deve permitir letras.

Campo Inscrição Estadual não possui regra de número de dígitos.

**Comment by VinieSantana** [comment]
Correções no sistema web efetuadas e feito o pull request. Necessário fazer também alterações no banco de dados, para se adaptar as mudanças.

**Comment by renanlf** [comment]
Alterações feitas no pull request #68

**Comment by renanlf** [comment]
@aprix , pode fechar a issue?

**Comment by aprix** [comment]
Acho que ainda tem algumas mensagens de erro que devem ser melhoradas.

**Comment by aprix** [comment]
Mias tarde testo novamente.

**Comment by renanlf** [comment]
Então vou repassar para @VinieSantana
