### ISSUE TITLE
WebService - Função de login.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#71]
A entrada será um JSON: 
{"CPF": "00011122233", "Password":"MD5"}.

A reposta deverá trazer as seguintes informações do usuário, caso sucesso:
{"Id":inteiro, "Nickname": "Apelido", "Email": "..."}

A reposta de erro de login:
{"Error": "Email ou senha inválidos"}

**Comment by renanlf** [comment]
Implementada solicitação no pull request #75 , favor verifiquem.

**Comment by DiogoEspinhara** [comment]
Alterar a key "Cpf" para "CPF". Na resposta colocar a primeira letra maiúscula, exemplo: "id" -> "Id".

**Comment by DiogoEspinhara** [comment]
No comando condicional, abaixo, faltou o bloco ELSE retornando erros de SQL:

if ($query = mysqli_query($this->db, $sql)){
   ...........
}

**Comment by DiogoEspinhara** [comment]
Na função que retorna o comando Select do login, abaixo, faltou colocar as variáveis $cpf e $password entre '' (apóstrofos).

function select_user($cpf, $password){
    return "SELECT user.id, user.nickname, user.email
            FROM user
            WHERE user.cpf = $cpf AND user.senha = $password";
}

**Comment by renanlf** [comment]
Pode fechar a issue @DiogoEspinhara ?
