### ISSUE TITLE
WebService - Função para Compra de Créditos.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#72]
Entrada: {"IdUser": inteiro, "IdCreditCard": inteiro, "Value": double}

Resposta para sucesso: {"Sucess": "Pode ser vazio aqui"}

Resposta para erros: {"Error": "Mensagem do erro"}

**Comment by renanlf** [comment]
@DiogoEspinhara , no caso seria só incrementar o campo saldo da tabela, correto?

**Comment by DiogoEspinhara** [comment]
E armazenar o registro da compra.

**Comment by DiogoEspinhara** [comment]
A entrada deverá conter o CSC do cartão, portanto, a entrada será:
{"IdUser": inteiro, "IdCreditCard": inteiro, "CSC": "000", "Value": double}

**Comment by DiogoEspinhara** [comment]
Mudar o nome da função para post_buy_credits ou outro nome similar. O nome atual pode ocasionar confusão com a compra de tíquetes.

**Comment by renanlf** [comment]
@DiogoEspinhara , funcionou corretamente a função?

**Comment by DiogoEspinhara** [comment]
Sim @renanlf , vou fechar a issue.
