### ISSUE TITLE
WebService - Função Pagamento de Estacionamento para Usuário Cadastrado.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#73]
Entrada: {"idUser": inteiro, "Plate": "Placa", "Time": "Tempo em minutos"}

Resposta para sucesso: {"Sucess": "Data/Hora final do estacionamento (limite)"}

Resposta para Falha: {"Error": "Mensagem contendo o erro"}

**Comment by DiogoEspinhara** [comment]
Sugestão de nome: post_vacancy_location_user

**Comment by renanlf** [comment]
@DiogoEspinhara , temos uma tabela no banco para os veículos, no caso não seria o id do veículo passado ao Webservice?

**Comment by DiogoEspinhara** [comment]
Não, eu não tenho essa informação no APP, o WebService que deverá buscar o Id do veículo através da placa.

**Comment by renanlf** [comment]
Ok, quando validar o último pull request eu faço esta função.
@DiogoEspinhara

**Comment by renanlf** [comment]
Vou trabalhar nesta issue agora @DiogoEspinhara .

**Comment by renanlf** [comment]
@DiogoEspinhara os veiculos não cadastrados para o usuário IdUser, serão cadastrados nesta função ou deverão ser cadastrados previamente?

**Comment by DiogoEspinhara** [comment]
Os novos veículos serão cadastrados dentro da função mesmo.

**Comment by DiogoEspinhara** [comment]
Implementar a renovação de vaga: 
1) Remover a validação "Veículo já estacionado";
2) Validar se o novo tempo do tíquete satisfaz o tempo máximo permitido;
     Mensagem: "Veículo já estacionado, tempo máximo permitido já adquirido" - pode mudar se quiser.
3) Atualizar o registro do tíquete aberto para o veículo, incrementar o tempo do tíquete com o tempo adicional adquirido;

**Comment by DiogoEspinhara** [comment]
Não está considerando o desconto para vendedores.

**Comment by renanlf** [comment]
Como assim?
Em 27/11/2015 10:45 PM, "DiogoEspinhara" notifications@github.com
escreveu:

**Comment by DiogoEspinhara** [comment]
O desconto não é aplicado ao preço unitário quando o usuário que está pagando o tíquete é um vendedor. Aplicar o desconto ao preço unitário no comando de atribuição:
$value = $time \* $un_price;

Obs.: lembrando que o desconto só é aplicado aos usuários que são vendedores.

**Comment by renanlf** [comment]
Beleza, irei fazer isso
Em 28/11/2015 12:07 AM, "DiogoEspinhara" notifications@github.com
escreveu:
