### ISSUE TITLE
WebService - Função para consultar os créditos de determinado usuário.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#77]
Nome da função: get_credits_user

Entrada: {"IdUser": inteiro}

Saída - Sucesso: {"Value": Total de Créditos}

Saída - Erro: {"Error": "Mensagem do erro"}

**Comment by renanlf** [comment]
@DiogoEspinhara issue solicitada foi implementada, por favor verificar.
