### ISSUE TITLE
WebService - Função para consultar os 10 últimos tíquetes de um usuário cadastrado.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#79]
Sugestão de nome: get_vacancy_location_user.

Entrada: {"IdUser": Inteiro}

Saída - Sucesso: 
[ {"Plate": "Placa", "StartTime": "Data de Início", "Time": Inteiro - Tempo em minutos}
, ...
, {"Plate": "Placa", "StartTime": "Data de Início", "Time": Inteiro - Tempo em minutos}]

Saída - Erro:
{"Error": "Mensagem do erro"}

Obs.: somente os 10 últimos tíquetes do usuário deverá ser retornado pela função.

**Comment by DiogoEspinhara** [comment]
Remover o retorno de erro quando o usuário não tem tíquetes já adquiridos. Nesse caso, retorne o vetor vazio, ou seja, um JSONArray vazio ( [] ).

**Comment by renanlf** [comment]
@DiogoEspinhara , funcionou como esperada a função?

**Comment by DiogoEspinhara** [comment]
Sim @renanlf . Vou fechar a issue.
