### ISSUE TITLE
WebService - Função post_vacancy_location.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#8]
O parâmetro validate deverá ser quebrado em dois - MonthCreditCard e YearCreditCard.

O JSON com a resposta deverá conter o par de chave "Sucess", cujo valor é a data do tíquete(locação de vaga) atribuído ao registro inserido no banco de dados.

Ex.: $response['Sucess'] = "Data cujo formato é dia/mês/ano hora:minuto:segundo";

**Comment by renanlf** [comment]
O pull request #9 visa resolver este problema. Favor verificar se está funcionando.
