### ISSUE TITLE
WebService - Função para consulta dos atributos da tabela de preços.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#94]
Entrada: {"IdUser": Inteiro} //necessário para carregar ou não o desconto de vendedor.

Saída: {"PriceTime": Valor, "MinTime": TempoMínimo, " MaxTime": TempoMáximo, "UnitTime": UnidadeMinutos, "DiscountPrice": DescontoVendedor}

OBS.: o desconto deverá retomar zero para usuários que não são vendedores.

**Comment by DiogoEspinhara** [comment]
Corrigir este comando de atribuição:
$response['PriceTime']     = $row['un_price'];

**Comment by renanlf** [comment]
Por quê?
Em 27/11/2015 5:11 PM, "DiogoEspinhara" notifications@github.com escreveu:

**Comment by DiogoEspinhara** [comment]
Desconsidere, já removi o comentário. Foi um equívoco. :)
Em 27/11/2015 6:14 PM, "Renan Leandro Fernandes" notifications@github.com
escreveu:
