### ISSUE TITLE
WebService - Função para pagamento de estacionamento para usuário avulso.

### ISSUE THREAD

**Issue by DiogoEspinhara** [aprix/projetao20152uag#95]
Implementar a renovação de vaga: 
1) Remover a validação "Veículo já estacionado";
2) Validar se o novo tempo do tíquete satisfaz o tempo máximo permitido;
     Mensagem: "Veículo já estacionado, tempo máximo permitido já adquirido" - pode mudar se quiser.
3) Atualizar o registro do tíquete aberto para o veículo, incrementar o tempo do tíquete com o tempo adicional adquirido;

**Comment by renanlf** [comment]
É para o usuário avulso? O que não possui cadastro esta alteração @DiogoEspinhara ?

**Comment by DiogoEspinhara** [comment]
@renanlf  não entendi a pergunta.

**Comment by renanlf** [comment]
É para fazer esta alteração nos pagamentos avulsos? Ou foi por engano?

**Comment by DiogoEspinhara** [comment]
Sim, fazer a alteração também para pagamentos avulsos.

**Comment by DiogoEspinhara** [comment]
Só falta remover o comando echo $sql_update_vacancy_location. Após a remoção fecharei a issue.

**Comment by renanlf** [comment]
Feito.
Em 25/11/2015 4:29 PM, "DiogoEspinhara" notifications@github.com escreveu:
